builtin: fix random number if low > 6
stanford-oval/genie-toolkit pull request #475
Opened 2021-02-15 17:13 UTC by gcampax

If low > high (which defaults to 6), the existing math is incorrect.
Instead, if low > high, raise the high to low + 6, keeping the default
range in case the user only specifies high.

Fixes #474

2021-02-15 17:57 UTC, rayslxu approved these changes
It's a little weird to get only numbers between 100 and 106 when user asking a random number greater than 100. But let's at least don't generate the wrong number first.

2021-02-15 18:04 UTC, gcampax commented
Do you have a different suggestion for how to choose an upper bound if only a lower bound is specified?

Also, one quirk of the old code is that the math works out correctly if you swap high and low (ie, you always get a number between the smaller and the larger of the two numbers). This quirk papers over bad parses.
With this change, the quirk is no more.

2021-02-15 20:07 UTC, s-jse requested changes
This does not support negative numbers: the default low should not be 1, if it is not specified but high is specified, it should be determined using the default range.

And a slightly better default range is 2*abs(low). So "a random number above 100" will be between (100, 200) and "a random number above -10" will be (-10, 10).

2021-02-17 17:15 UTC, gcampax commented
@s-jse take a look at the revised implementation, see if this makes more sense to you.

2021-02-18 22:10 UTC, s-jse commented on lib/engine/devices/builtins/thingengine.builtin.ts
> +        } else if (low === null || low === undefined) {
Maybe something like this?
```
else if (low === null || low === undefined) {
            low = high! < 0 ? min(2 * high!, high!-5) : 1;
        } else if (high === null || high === undefined) {
            high = low < 0 ? 0 : max(2 * low, low+5);
        }
```

2021-02-18 22:10 UTC, s-jse approved these changes

2021-02-19 02:07 UTC, merged